namespace fBaseXtensions.Items.Enums
{
	public enum LegendaryItemTypes
	{
		None,


		//Belts
		Goldwrap,
		VigilanteBelt,
		QuickDrawBelt,
		SaffronWrap,
		StringofEars,
		CordoftheSherma,
		HarringtonWaistguard,
		HwojWrap,
		RazorStrop,
		SashofKnives,
		SeborsNightmare,
		AngelHairBraid,
		ThundergodsVigor,
		HellcatWaistguard,
		TheWitchingHour,
		JangsEnvelopment,
		FleetingStrap,
		InsatiableBelt,

		//Boots
		LutSocks,
		TheCrudestBoots,
		BojAnglers,
		IrontoeMudsputters,
		FireWalkers,
		LostBoys,
		IceClimbers,
		BoardWalkers,
		IllusionaryBoots,
		BootsofDisregard,

		//Bracers
		GungdoGear,
		SteadyStrikers,
		SlaveBonds,
		AncientParthanDefenders,
		CusterianWristguards,
		NemesisBracers,
		WarzechianArmguards,
		PromiseofGlory,
		LacuniProwlers,
		StrongarmBracers,
		WondrousDeflectors,
		TragOulCoils,
		KethryesSplint,
		ReapersWraps,
		SanguinaryVambraces,

		//Chest
		AquilaCuirass,
		HeartofIron,
		Chaingmail,
		Cindercoat,
		ShiMizusHaori,
		Goldskin,
		TyraelsMight,
		RobesoftheRydraelm,
		ArmoroftheKindRegent,
		MantleoftheRydraelm,

		//Cloaks
		BeckonSail,
		Blackfeather,
		TheCloakoftheGarwulf,
		CapeoftheDarkNight,
		CloakofDeception,

		//Gloves
		StoneGauntlets,
		Magefist,
		StArchewsGage,
		Pendergrasps,
		GladiatorGauntlets,
		Frostburn,
		TaskerandTheo,
		PendersPurchase,
		GlovesofWorship,

		//Helms
		BrokenCrown,
		LeoricsCrown,
		BlindFaith,
		DeathseersCowl,
		SkullofResonance,
		AndarielsVisage,
		MempoofTwilight,
		TheHelmofCommand,
		TheHelmofRule,
		PridesFall,

		//Mighty Belts
		GirdleofGiants,
		TheUndisputedChampion,
		KotuursBrace,
		PrideofCassius,
		ChilaniksChain,
		DreadIron,
		AgelessMight,
		Lamentation,

		//Pants
		PoxFaulds,
		HammerJammers,
		HexingPantsofMrYan,
		SwampLandWaders,
		DepthDiggers,
		Gehennas,
		SkelonsDeceit,
		DeathsBargain,

		//Shoulders
		HomingPads,
		DeathWatchMantle,
		ProfanePauldrons,
		SpauldersofZakara,
		VileWard,
		SevenSins,
		Corruption,
		PauldronsoftheSkeletonKing,

		//Spirit Stones
		SeeNoEvil,
		GyanaNaKashu,
		ErlangShen,
		TheMindsEye,
		EyeofPeshkov,
		KekegisUnbreakableSpirit,
		TheLawsofSeph,
		BezoarStone,
		TheEyeoftheStorm,
		Madstone,
		TzoKrinsGaze,

		//Voodoo Masks
		SplitTusk,
		Quetzalcoatl,
		Carnevil,
		MaskofJeram,
		TheGrinReaper,
		TiklandianVisage,
		VisageofGiyua,

		//Wizard Hats
		TheSwami,
		DarkMagesShade,
		ArchmagesVicalyke,
		TheMagistrate,
		VelvetCamaral,
		StormCrow,




		//Amulets
		MoonlightWard,
		SquirtsNecklace,
		EyeofEtlich,
		RondalsLocket,
		TalismanofAranoch,
		AncestorsGrace,
		CountessJuliasCameo,
		DovuEnergyTrap,
		HauntofVaxo,
		RakoffsGlassofLife,
		TheEssofJohan,
		HolyBeacon,
		KymbosGold,
		TheFlavorofTime,
		MarasKaleidoscope,
		Ouroboros,
		TheStarofAzkaranth,
		XephirianAmulet,
		HalcyonsAscent,
		OverwhelmingDesire,
		GoldenGorgetofLeoric,
		HellfireAmulet,

		//Rings
		HellfireRing,
		ManaldHeal,
		Nagelring,
		StolenRing,
		LeoricsSignet,
		BandofUntoldSecrets,
		BrokenPromises,
		PuzzleRing,
		BandoftheRueChambers,
		RechelsRingofLarceny,
		RogarsHugeStone,
		TheTallMansFinger,
		Wyrdward,
		BulKathossWeddingBand,
		EternalUnion,
		JusticeLantern,
		ObsidianRingoftheZodiac,
		BandofHollowWhispers,
		KredesFlame,
		OculusRing,
		SkullGrasp,
		StoneofJordan,
		Unity,
		RingofRoyalGrandeur,
		AvariceBand,
		PandemoniumLoop,
		
		//Shields
		Denial,
		WallofBone,
		DefenderofWestmarch,
		EberliCharo,
		FreezeofDeflection,
		VoToyiasSpiker,
		LidlessWall,
		IvoryTower,
		Stormshield,
		WallofMan,
		CovensCriterion,

		//Crusader Shields
		AkaratsAwakening,
		HallowedBulwark,
		Hellskull,
		Jekangbord,
		SublimeConviction,
		TheFinalWitness,
		PiroMarella,
		Salvation,

		//Mojos
		GazingDemise,
		Homunculus,
		Bitterness,
		ShukranisTriumph,
		ThingoftheDeep,
		UhkapianSerpent,
		Spite,

		//Sources
		WinterFlurry,
		LightofGrace,
		Mirrorball,
		MykensBallofHate,
		Singularity,
		TheOculus,
		Triumvirate,
		CosmicStrand,

		//Quivers
		FletchersPride,
		SinSeekers,
		HolyPointShot,
		SilverStarPiercers,
		BombadiersRucksack,
		EmimeisDuffel,
		TheNinthCirriSatchel,
		FlintRipperArrowheads,
		DeadMansLegacy,
		BlackBoneArrows,
		ArchfiendArrows,

		//Axe
		Genzaniku,
		TheWedge,
		FleshTearer,
		Hack,
		TheButchersSickle,
		TheBurningAxeofSankis,
		SkySplitter,
		UtarsRoar,

		//Ceremonial Knife
		DeadlyRebirth,
		MoonSlayer,
		UmbralOath,
		RhenhoFlayer,
		TheSpiderQueensGrasp,
		StarmetalKukri,
		ZigguratTooth,
		AnessaziEdge,
		TheGidbinn,
		LastBreath,
		LivingUmbralOath,

		//Daggers
		TheBarber,
		TheHoradricHamburger,
		PigSticker,
		Kill,
		BloodMagicBlade,
		Wizardspike,
		BloodMagicEdge,
		EnviousBlade,

		//Fist Weapons
		RabidStrike,
		Fleshrake,
		Scarbringer,
		Sledgefist,
		Jawbreaker,
		DemonHand,
		LogansClaw,
		WonKhimLau,
		CrystalFist,
		TheFistofAzTurrasq,
		DemonClaw,
		SledgeFist,
		VengefulWind,

		//Flails
		Darklight,
		GyrfalconsFoote,
		InviolableFaith,
		JustiniansMercy,
		KassarsRetribution,
		Swiftmount,
		GoldenScourge,

		//Hand Crossbow
		Deadeye,
		Izzuccob,
		BalefireCaster,
		KmarTenclip,
		Dawn,
		Calamity,
		Blitzbolter,
		Helltrapper,

		//Mace
		OdynSon,
		Nutcracker,
		TelrandensHand,
		Neanderthal,
		JacesHammerofVigilance,
		Solanium,
		Nailbiter,
		Earthshatter,
		EchoingFury,
		SunKeeper,
		Devastator,
		MadMonarchsScepter,
		

		//MightyWeapon
		FjordCutter,
		AmbosPride,
		HarvestMoon,
		BladeoftheWarlord,
		NightsReaping,

		//Spear
		Scrimshaw,
		ArreatsLaw,
		TheThreeHundredthSpear,
		EmpyreanMessenger,

		//Sword
		MonsterHunter,
		Spectrum,
		Wildwood,
		TheAncientBonesaberofZumakalis,
		Doombringer,
		Exarian,
		Fulminator,
		GiftofSilaria,
		Rimeheart,
		ThunderfuryBlessedBladeoftheWindseeker,
		Skycutter,
		GriswoldsMasterpiece,
		Sever,
		Azurewrath,
		DevilTongue,
		ShardofHate,
		GriswoldsPerfection,

		//Wand
		Starfire,
		BlackhandKey,
		SerpentSparker,
		WandofWoh,
		GestureofOrpheus,
		FragmentofDestiny,
		Ruinstoke,
		SloraksMadness,
		Atrophy,

		//Bow
		Uskang,
		Longshot,
		TheRavensWing,
		Etrayu,
		Kridershot,
		Cluckeye,
		Venomhusk,
		Windforce,
		SydyruCrust,
		UnboundBolt,

		//Crossbow
		BakkanCaster,
		DemonMachine,
		BurizaDoKyanon,
		Starspine,
		PusSpitter,
		Hellrack,
		Manticore,
		ChanonBolter,
		ArcaneBarb,

		//Daibo
		Balance,
		LaiYuisTaiji,
		TheFlowofEternity,
		StaffofKyro,
		WarstaffofGeneralQuang,
		TheCloudsandtheMoon,
		ThePaddle,
		IncenseTorchoftheGrandTemple,
		RozpedinsStaff,
		FlyingDragon,
		LaiYuisPersuader,
		RozpedinsForce,

		//Polearm
		PledgeofCaldeum,
		Standoff,
		HeartSlaughter,
		Vigilance,
		BovineBardiche,

		//Staff
		AutumnsCall,
		TheMagi,
		TheBrokenStaff,
		MalothsFocus,
		Wormwood,
		TheTormentor,
		TheGrandVizier,
		Ahavarion, 
		SpearofLycander,
		TheSmolderingCore,
		ValtheksRebuke,
		MarkofTheMagi,

		//Two-HandedAxe
		TheExecutioner,
		ButchersCarver,
		MesserschmidtsReaver,
		FireBrand,
		Skorn,
		CinderSwitch,

		//Two-HandedFlail
		BalefulRemnant,
		FateoftheFell,
		GoldenFlense,
		TheMortalDrama,


		//Two-HandedMace
		Boneshatter,
		Crushbane,
		WrathoftheBoneKing,
		Skywarden,
		Cataclysm,
		SledgeofAthskeleng,
		SchaeferssHammer,
		ArthefsSparkofLife,
		TheFurnace,
		Sunder,
		Soulsmasher,

		//Two-HandedMightyWeapon
		UnendingWar,
		BastionsRevered,
		TheGavelofJudgment,
		FuryoftheVanishedPeak,
		MadawcsSorrow,
		WaroftheDead,


		//Two-HandedSword
		TheZweihander,
		FaithfulMemory,
		Scourge,
		Blackguard,
		BladeofProphecy,
		TheSultanofBlindingSand,
		Warmonger,
		Maximus,
		TheGrandfather,
		StalgardsDecimator,
		CamsRebuttal,

		//SETS
		BlackthornesBattlegear,
		ZunimassasHaunt,
		ArmorofAkkhan,
		EmbodimentoftheMarauder,
		InnasMantra,
		VyrsAmazingArcana,
		RaimentoftheJadeHarvester,
		MightOfTheEarth,
		RaimentofaThousandStorms,

		BornsDefiance,
		BornsCommand,
		CainsDestiny,
		CainsFate,
		AughildsAuthority,
		AughildsVictory,
		GuardiansJeopardy,
		GuardiansContingency,
		DemonsHide,
		DemonsSkin,
		AshearasVestments,
		AshearasUniform,
		SagesJourney,
		SagesPlight,

		ImmortalKingsCall,
		NatalyasVengeance,
		TalRashasElements,
		ThornsoftheInvoker,
		MightoftheEarth,
		FirebirdsFinery,
		HelltoothHarness,
		TheLegacyofRaekor,
		MonkeyKingsGarb,
		CaptainCrimsonsTrimmings,
		TheShadowsMantle,
		EndlessWalk,
		HallowedProtectors,
		BastionsofWill,
		LegacyofNightmares,
		ManajumasWay,
		ChantodosResolve,
		BulKathossOath,
		ShenlongsSpirit,
		IstvansPairedBlades,
		
		KrelmsBuffBulwark,
	}
}
